name: 'Build an R package site'
description: 'Build an R package site with litedown that includes the description, news, manuals, vignettes, and citation, etc.'
inputs:
  site-dir:
    description: 'Directory of the site source'
    default: 'site'
  pkg-root:
    description: 'Root directory of the R package in the repository'
    default: '.'
  exclude:
    description: 'Pages to be excluded (filenames separated by spaces)'
    default: 'code.Rmd'
  cleanup:
    description: 'Command to clean up the site directory before publishing, e.g., you can delete the `.Rmd` source files'
    default: 'rm -f *.Rmd *.yml _*'
runs:
  using: "composite"
  steps:
    - name: Install R
      uses: r-lib/actions/setup-r@HEAD
      with:
        use-public-rspm: true
    - name: Install R package dependencies
      uses: yihui/actions/setup-r-dependencies@HEAD
      with:
        extra-packages: litedown xfun .
        r-universe: yihui
    - name: Build site
      shell: bash
      run: |
        cd "${{ inputs.pkg-root }}"
        mkdir -p "${{ inputs.site-dir }}"
        cd "${{ inputs.site-dir }}"
        [ -z "$(ls -A)" ] && cp -r "${{ github.action_path }}"/* ./
        [ -d "$OLDPWD/vignettes" ] || rm -f articles.Rmd
        [ -f "$OLDPWD/NEWS.md" ] || [ -f "$OLDPWD/inst/NEWS.Rd" ] || rm -f news.Rmd
        if [ -d "$OLDPWD/examples" ]; then
          cp -r "$OLDPWD/examples" ./
        else
          rm -f examples.Rmd
        fi
        [ -f "_footer.Rmd" ] && Rscript -e "litedown::fuse('_footer.Rmd', '.md')"
        rm -f ${{ inputs.exclude }}
        Rscript -e "litedown::fuse_site()"
        [ -d "$OLDPWD/playground" ] && cp -r "$OLDPWD/playground/." playground
        if [ -d "examples" ]; then
          ls examples | grep -E '^[^_]' | grep -E '[.](Rmd|R)$' > playground/examples.txt
        fi
        ${{ inputs.cleanup }}
