---
title: "`{r} pkg_name`: `{r} packageDescription(pkg_name, fields = 'Title')`"
date: "`{r} Sys.Date()`"
---

```{r, order = 0, include = FALSE}
litedown::reactor(echo = FALSE)
# package description
pkg_name = litedown:::detect_pkg()
pkg_path = attr(pkg_name, 'path')
# if man/figures exists and used, copy it to current dir
fig = file.path(pkg_path, 'man/figures')
if (!xfun::same_path('.', pkg_path) && dir.exists(fig)) {
  xfun::dir_create('man')
  file.copy(fig, 'man', recursive = TRUE)
}
```

```{r}
litedown::pkg_desc(pkg_name)
```

```{r, results = 'asis'}
# readme, if exists
if (file.exists(readme <- file.path(pkg_path, 'README.md'))) {
  x = xfun::read_utf8(readme)
  i = which(x == '<!-- badges: start -->')
  # remove lines before badges since they usually contain duplicated info (e.g., title)
  if (length(i)) x = x[-seq_len(i[1] - 1)]
  xfun::raw_string(x)
}
```

## Appendix {.appendix}

To cite the package **`{r} pkg_name`** in publications, please use:

```{r, warning = FALSE}
litedown::pkg_citation(pkg_name)
```
