# Appendix {.appendix}

# Miscellaneous Topics {#apd:misc}

## For rmarkdown users {#sec:rmarkdown}

The **litedown** package can partially recognize the output format names
`html_document`, `html_vignette`, and `pdf_document` from **rmarkdown**: Some
options of these output formats are mapped to **litedown**'s options internally.

For example, for an R Markdown document with the following output format:

``` yaml
output:
  html_document:
    toc: true
    number_sections: true
    anchor_sections: true
    self_contained: false
```

It will be transformed to:

``` yaml
output:
  html:
    options:
      toc: true
      number_sections: true
      embed_resources: false
    meta:
      css: ["default", "@heading-anchor"]
      js: ["@heading-anchor"]
```

Note that not all **rmarkdown** options are supported, and not even all
supported options have exactly the same effects in **litedown**. The supported
options include:
`` {r} xfun::join_words(setdiff(names(formals(litedown:::map_args)), '...'), before='`') ``.

## File or text output {#sec:file-text}

By default, `mark()` and `fuse()` follow the rule of "file in, file out; text
in, text out". That is, if you pass an input file, you get an output file. If
you pass text input, you get text output. For example:

``` r
fuse('foo.Rmd')  # returns a file 'foo.html' or 'foo.tex', etc.
mark('Hello _world_')  # returns text
mark(text = 'Hello _world_')  # text
```

You always get a file output if the argument `output` is a file path. If the
`output` argument is not a character string (e.g., `NA`), or it is a format name
(one of
`` {r} xfun::join_words(names(litedown:::md_formats), before = '`', and = 'or ') ``),
the output will be text. For example:

``` r
fuse('$\\pi$ = `{r} pi`', output = 'foo.pdf')  # file
mark('foo.md', output = NA)  # text
mark('foo.md', output = 'latex')  # text (LaTeX code)
```

If the input is a file and the `output` argument takes a file extension (one of
`` {r} xfun::join_words(litedown:::md_formats, before = '`', and = 'or ') ``),[^a-misc-1]
you will get a file output with the same base name as the input file. The `.pdf`
extension can also be used if you want to convert Markdown to LaTeX, and then
render LaTeX to PDF. For example:

[^a-misc-1]: Note that the format name `commonmark` and the extension
    `.markdown` are for CommonMark output. It should be rare that you need to
    convert Markdown input to CommonMark output, but it is possible anyway.

``` r
mark('foo/bar.md', output = '.html')  # file 'foo/bar.html'
mark('foo/bar.md', output = '.pdf')   # file 'foo/bar.pdf'
```

For `fuse()`, the `output` argument can take a special value of the form
`markdown:format`, where `format` is a format name. This value means to generate
the intermediate Markdown text for the target output format, e.g.,

``` r
fuse('foo.Rmd', output = 'markdown:latex')
```

Depending on the target output format, the intermediate Markdown may be
different, e.g., for `html` output, the default graphical device is PNG, whereas
for `latex` output, the default device is PDF.

@tab:input-output provides a summary of the above rules.

:::: {#tab:input-output .table}
::: caption
[ ](#@tab:input-output) The returned value for different combinations of `input`
and `output` arguments of `mark()` / `fuse()`.
:::

| function | `input` | `output` | returned value |
|----|----|----|----|
| `mark()` / `fuse()` | file | `NULL` | file |
|  | text | `NULL` | text |
|  | \* | file | file |
|  | \* | `NA` / `format` | text |
|  | `file.xxx` | `.ext` | `file.ext` |
|  | `file.xxx` | `.pdf` | `file.pdf` |
| `fuse()` | \* | `markdown` | intermediate Markdown text |
|  | \* | `.md` | intermediate Markdown file |
|  | \* | `markdown:format` | intermediate Markdown text for `format` |
::::

## Package vignettes {#sec:vignettes}

To build package vignettes with **litedown**, first add this to the package
`DESCRIPTION` file:

``` yaml
VignetteBuilder: litedown
```

If your package does not require **litedown** as a hard dependency (specified in
`Depends` or `Imports`), you will need to add it to `Suggests` in `DESCRIPTION`:

``` yaml
Suggests: litedown
```

Then use the vignette engine `litedown::vignette` in the YAML metadata of a
`.Rmd` or `.md` vignette file:

``` yaml
vignette: >
  %\VignetteEngine{litedown::vignette}
  %\VignetteIndexEntry{Your vignette title}
  %\VignetteEncoding{UTF-8}
```

The output format of a vignette can be specified in the `output` field of the
YAML metadata, e.g., `html` (for HTML vignettes) or `latex` (for PDF vignettes).
If no output format is specified, the default is HTML.

The vignette file can be either `.Rmd` or `.md`. The former is processed by
`litedown::fuse()`, and the latter is converted by `litedown::mark()`. Please
avoid using the same base filename for two `.Rmd` and `.md` files, otherwise
their output files will overwrite each other.
