name: Build and deploy package site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@HEAD
      - uses: actions/configure-pages@HEAD
        with:
          enablement: true
      - uses: r-lib/actions/setup-r@HEAD
        with:
          use-public-rspm: true
      - uses: yihui/actions/setup-r-dependencies@HEAD
      - uses: yihui/litedown/site@HEAD
        with:
          site-dir: 'site'
      - name: Add playground to site
        run: |
          cp -r playground site/playground
          cd examples && ls [0-9]*.Rmd | sort > ../site/playground/examples.txt
      - uses: actions/upload-pages-artifact@HEAD
        with:
          path: 'site'
      - id: deployment
        uses: actions/deploy-pages@HEAD
