on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: '4.3'}
          - {os: ubuntu-latest,   r: '4.2'}
          - {os: ubuntu-latest,   r: '4.1'}
          - {os: ubuntu-latest,   r: '4.0'}
          - {os: ubuntu-latest,   r: '3.6'}
          - {os: ubuntu-latest,   r: '3.5'}
          - {os: ubuntu-latest,   r: '3.4'}
          - {os: ubuntu-latest,   r: '3.3'}
          - {os: ubuntu-latest,   r: '3.2'}
          - {os: ubuntu-latest,   r: '3.2.0'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false
      _R_CHECK_RD_XREFS_: false

    steps:
      - uses: actions/checkout@HEAD

      - uses: r-lib/actions/setup-pandoc@HEAD

      - uses: r-lib/actions/setup-r@HEAD
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install dependencies for cairo_pdf device
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz

      - uses: r-lib/actions/setup-r-dependencies@HEAD
        if: matrix.config.r >= '4.0'
        with:
          # install the package itself as we register vignette engine
          extra-packages: any::rcmdcheck, local::.
          needs: check

      - uses: r-lib/actions/check-r-package@HEAD
        if: matrix.config.r >= '4.0'
        with:
          upload-snapshots: true

      - name: Check against R < 4.0
        if: matrix.config.r < '4.0'
        run: |
          Rscript .github/workflows/deps.R
          R CMD INSTALL .
          cd ..
          R CMD build litedown
          R CMD check --as-cran --no-manual litedown_*.tar.gz

      - uses: actions/checkout@HEAD
        if: runner.os == 'macOS'
        with:
          path: gh-pages
          ref: gh-pages

      - name: Publish documentation
        if: runner.os == 'macOS'
        run: |
          Rscript -e 'litedown::fuse_book("docs")'
          cd docs; cp -r *.html ../gh-pages/; cd ../gh-pages
          git config user.name "Yihui Xie"
          git config user.email "xie@yihui.name"
          git add .
          git commit -m "update docs" && git push || true
