on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'old-1'}
          - {os: ubuntu-latest,   r: 'old-2'}
          - {os: ubuntu-latest,   r: 'old-3'}
          - {os: ubuntu-latest,   r: 'old-4'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # install the package itself as we register vignette engine
          extra-packages: any::rcmdcheck, local::.
          needs: check

      - name: Install dependencies for cairo_pdf device
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - uses: actions/checkout@v3
        if: runner.os == 'macOS'
        with:
          path: gh-pages
          ref: gh-pages

      - name: Publish documentation
        if: runner.os == 'macOS'
        run: |
          Rscript -e 'litedown::fuse_book("docs")'
          cd docs; cp -r *.html ../gh-pages/; cd ../gh-pages
          git config user.name "Yihui Xie"
          git config user.email "xie@yihui.name"
          git add .
          git commit -m "update docs" && git push || true
