# check the package against older versions of R

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-old-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: '3.2.0'}
          - {os: ubuntu-latest,   r: '3.2.1'}
          - {os: ubuntu-latest,   r: '3.2.2'}
          - {os: ubuntu-latest,   r: '3.2.3'}
          - {os: ubuntu-latest,   r: '3.2.4'}
          - {os: ubuntu-latest,   r: '3.2.5'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@HEAD

      - uses: r-lib/actions/setup-tinytex@HEAD

      - uses: r-lib/actions/setup-r@HEAD
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript .github/workflows/deps.R

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@HEAD
        if: matrix.config.r == '3.0.0'

      - name: R CMD check
        shell: bash
        run: |
          R CMD INSTALL .
          cd ..
          R CMD build litedown
          R CMD check --as-cran litedown_*.tar.gz
