# check the package against older versions of R

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-old-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: '3.6'}
          - {os: ubuntu-latest,   r: '3.5'}
          - {os: ubuntu-latest,   r: '3.4'}
          - {os: ubuntu-latest,   r: '3.3'}
          - {os: ubuntu-latest,   r: '3.2'}
          - {os: ubuntu-latest,   r: '3.2.0'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false
      _R_CHECK_RD_XREFS_: false

    steps:
      - uses: actions/checkout@HEAD

      - uses: r-lib/actions/setup-tinytex@HEAD

      - uses: r-lib/actions/setup-r@HEAD
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript .github/workflows/deps.R
          R CMD INSTALL .

      - name: R CMD check
        run: |
          cd ..
          R CMD build litedown
          R CMD check --as-cran --no-manual litedown_*.tar.gz
